//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdicionesxCliente
    {
        public int idAdicionesxCliente { get; set; }
        public Nullable<int> idAdicion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idRegistroPoliza { get; set; }
    }
}
